cachelocation: /var/tmp/metricsathome-cache

screenconfig:
  citytram:
    class: metricsathome.TramScreenV2.TramScreenV2
    duration: 60
    args:
      routeno: 109
      stopno: 1749
      firststopnum: 1725
      firststopname: "Daniel's Work"
      secondstopnum: 3508
      secondstopname: "Kate's Work"
  boxhilltram:
    class: metricsathome.TramScreenV2.TramScreenV2
    duration: 60
    args:
      routeno: 109
      stopno: 2749
      firststopnum: 2757
      firststopname: "Box Hill"
      secondstopnum: 2757
      secondstopname: "Box Hill"
  melbweather:
    class: metricsathome.WeatherScreen.WeatherScreen
    duration: 60
    args:
      radarcode: "023"
      weatherdistrict: "VIC_PT042"
      xmlfile: "IDV10753.xml" #From: http://www.bom.gov.au/info/precis_forecasts.shtml
  sydweather:
    class: metricsathome.WeatherScreen.WeatherScreen
    duration: 60
    args:
      radarcode: "713"
      weatherdistrict: "NSW_PT131"
      xmlfile: "IDN11060.xml" #From: http://www.bom.gov.au/info/precis_forecasts.shtml
  black:
    class: metricsathome.ColorScreen.ColorScreen
    duration: 5
    args:
      color: "#000000"
  white:
    class: metricsathome.ColorScreen.ColorScreen
    duration: 5
    args:
      color: "#FFFFFF"
  green:
    class: metricsathome.ColorScreen.ColorScreen
    duration: 5
    args:
      color: "#00c000"
  red:
    class: metricsathome.ColorScreen.ColorScreen
    duration: 5
    args:
      color: "#c00000"
  hello:
    class: metricsathome.HelloWorldScreen.HelloWorldScreen
    duration: 120
    args:
      text: "Hello Config!"
  clock:
    class: metricsathome.ClockScreen.ClockScreen
    duration: 1
    args:
  nightclock:
    class: metricsathome.ClockScreen.ClockScreen
    duration: 240
    args:
      textcolor: "#303030"
  weatherpicture:
    class: metricsathome.PicScreen.PicScreen
    duration: 15
    args:
      picture: 'docs/WeatherScreen.png'
  defaultpicture:
    class: metricsathome.PicScreen.PicScreen
    duration: 15
    args:
  trampic:
    class: metricsathome.PicScreen.PicScreen
    duration: 5
    args:
      picture: 'docs/Tram.png'
  rndmpic:
    class: metricsathome.RandomPicScreen.RandomPicScreen
    duration: 2
    args:
      pictures:
        - 'docs/Tram.png'
        - 'docs/WeatherScreen.png'
  mopcount:
    class: metricsathome.CountDownScreen.CountDownScreen
    duration: 30
    args:
      datetime: "Tue Sep 25 00:00:00 -0700 2012"
      event: "Mists of Pandaria"
  test:
    class: metricsathome.FridgeScreen.FridgeScreen
    duration: 15
    args:


defaultscreens:
- citytram
- boxhilltram
- test

screenschedule:

