cachelocation: /var/tmp/metricsathome-cache

screenconfig:
  hometrams:
    class: metricsathome.TramScreenV2.TramScreenV2
    duration: 60
    args:
      stopno: 1749
      routeno: 109
  melbweather:
    class: metricsathome.WeatherScreen.WeatherScreen
    duration: 60
    args:
      radarcode: "023"
      weatherdistrict: "VIC_PT042"
      xmlfile: "IDV10753.xml" #From: http://www.bom.gov.au/info/precis_forecasts.shtml
  sydweather:
    class: metricsathome.WeatherScreen.WeatherScreen
    duration: 60
    args:
      radarcode: "713"
      weatherdistrict: "NSW_PT131"
      xmlfile: "IDN11060.xml" #From: http://www.bom.gov.au/info/precis_forecasts.shtml
  black:
    class: metricsathome.ColorScreen.ColorScreen
    duration: 5
    args:
      color: "#000000"
  white:
    class: metricsathome.ColorScreen.ColorScreen
    duration: 5
    args:
      color: "#FFFFFF"
  green:
    class: metricsathome.ColorScreen.ColorScreen
    duration: 5
    args:
      color: "#00c000"
  red:
    class: metricsathome.ColorScreen.ColorScreen
    duration: 5
    args:
      color: "#c00000"
  hello:
    class: metricsathome.HelloWorldScreen.HelloWorldScreen
    duration: 120
    args:
      text: "Hello Config!"


defaultscreens:
- melbweather

screenschedule:
- hours:
  - 6
  - 7
  - 8
  - 9
  - 10
  - 11
  screens:
  - hometrams
  - melbweather
- hours:
  - 22
  - 23
  - 0
  - 1
  - 2
  - 3
  - 4
  - 5
  screens:
  - black

